require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/bp3-core.rb
